### ISSUE TITLE
Remote sonar

### ISSUE THREAD

**Issue by Pouja** [codeclimate/codeclimate-sonar-java#54]
Since the sonarlint cli page is removed, how can you specify your remote sonarqube, so that the quality profile is used for the given projectKey?

**Comment by filipesperandio** [comment]
Plugins don't have network access by design, so even if we build a way to support a remote sonar, it won't be reachable while analyzing.

https://github.com/codeclimate/codeclimate/issues/480

**Comment by Pouja** [comment]
Ah thanks for the info, I'll close this issue then.
